/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
AudioPluginAudioProcessorEditor::AudioPluginAudioProcessorEditor
    (AudioPluginAudioProcessor* ownerFilter)
    : AudioProcessorEditor (ownerFilter),
      midiKeyboard (ownerFilter->keyboardState, MidiKeyboardComponent::horizontalKeyboard),
      infoLabel (String::empty),
      gainLabel ("", "Throughput level:"),
      delayLabel ("", "Delay:"),
      gainSlider ("gain"),
      delaySlider ("delay"),
      sineWaveButton ("Sine Wave"),
      squareWaveButton ("Square Wave"),
      triangleWaveButton ("Triangle Wave"),
      sawToothWaveButton ("Saw Tooth Wave"),
      FMWaveButton ("Frequency Modulation Wave"),
      AMWaveButton ("Amplitude Modulation Wave"),
      FMixWaveButton ("Frequency Mixing Wave")
{
    // add some sliders..
    addAndMakeVisible (gainSlider);
    gainSlider.setSliderStyle (Slider::Rotary);
    gainSlider.addListener (this);
    gainSlider.setRange (0.0, 1.0, 0.01);
    
    addAndMakeVisible (delaySlider);
    delaySlider.setSliderStyle (Slider::Rotary);
    delaySlider.addListener (this);
    delaySlider.setRange (0.0, 1.0, 0.01);

    // add some labels for the sliders..
    gainLabel.attachToComponent (&gainSlider, false);
    gainLabel.setFont (Font (11.0f));
    
    delayLabel.attachToComponent (&delaySlider, false);
    delayLabel.setFont (Font (11.0f));
    
    // add some toggle buttons for the wave types..
    addAndMakeVisible (sineWaveButton);
    sineWaveButton.setToggleState(true, dontSendNotification);
    sineWaveButton.setRadioGroupId(1);
    sineWaveButton.addListener (this);

    addAndMakeVisible (squareWaveButton);
    squareWaveButton.setRadioGroupId(1);
    squareWaveButton.addListener (this);

    addAndMakeVisible (triangleWaveButton);
    triangleWaveButton.setRadioGroupId(1);
    triangleWaveButton.addListener (this);

    addAndMakeVisible (sawToothWaveButton);
    sawToothWaveButton.setRadioGroupId(1);
    sawToothWaveButton.addListener (this);
    
    addAndMakeVisible (FMWaveButton);
    FMWaveButton.setRadioGroupId(1);
    FMWaveButton.addListener (this);
    
    addAndMakeVisible (AMWaveButton);
    AMWaveButton.setRadioGroupId(1);
    AMWaveButton.addListener (this);
    
    addAndMakeVisible (FMixWaveButton);
    FMixWaveButton.setRadioGroupId(1);
    FMixWaveButton.addListener (this);
    
    // add the midi keyboard component..
    addAndMakeVisible (midiKeyboard);
    
    // add a label that will display the current timecode and status..
    addAndMakeVisible (infoLabel);
    infoLabel.setColour (Label::textColourId, Colours::blue);
    
    // add the triangular resizer component for the bottom-right of the UI
    addAndMakeVisible (resizer = new ResizableCornerComponent (this, &resizeLimits));
    resizeLimits.setSizeLimits (150, 150, 800, 300);
    
    // set our component's initial size to be the last one that was stored in the filter's settings
    setSize (ownerFilter->lastUIWidth,
             ownerFilter->lastUIHeight);
    
    startTimer (50);
}

AudioPluginAudioProcessorEditor::~AudioPluginAudioProcessorEditor()
{
}

//==============================================================================
void AudioPluginAudioProcessorEditor::paint (Graphics& g)
{
    g.setGradientFill (ColourGradient (Colours::white, 0, 0,
                                       Colours::grey, 0, (float) getHeight(), false));
    g.fillAll();
}

void AudioPluginAudioProcessorEditor::resized()
{
    infoLabel.setBounds (10, 4, 400, 25);
    gainSlider.setBounds (20, 60, 150, 40);
    delaySlider.setBounds (200, 60, 150, 40);
    sineWaveButton.setBounds(0, 120, 100, 20);
    squareWaveButton.setBounds(100, 120, 100, 20);
    triangleWaveButton.setBounds(200, 120, 100, 20);
    sawToothWaveButton.setBounds(300, 120, 100, 20);
    FMWaveButton.setBounds(50, 150, 100, 20);
    AMWaveButton.setBounds(150, 150, 100, 20);
    FMixWaveButton.setBounds(250, 150, 100, 20);
    
    const int keyboardHeight = 70;
    midiKeyboard.setBounds (4, getHeight() - keyboardHeight - 4, getWidth() - 8, keyboardHeight);
    
    resizer->setBounds (getWidth() - 16, getHeight() - 16, 16, 16);
    
    getProcessor()->lastUIWidth = getWidth();
    getProcessor()->lastUIHeight = getHeight();
}

//==============================================================================
// This timer periodically checks whether any of the filter's parameters have changed...
void AudioPluginAudioProcessorEditor::timerCallback()
{
    AudioPluginAudioProcessor* ourProcessor = getProcessor();
    
    AudioPlayHead::CurrentPositionInfo newPos (ourProcessor->lastPosInfo);
    
    if (lastDisplayedPosition != newPos)
        displayPositionInfo (newPos);
    
    gainSlider.setValue (ourProcessor->gain, dontSendNotification);
    delaySlider.setValue (ourProcessor->delay, dontSendNotification);
    float waveType = ourProcessor->waveType;
    
    if (waveType > -0.5 && waveType < 0.5) {
        sineWaveButton.setToggleState(true, dontSendNotification);
    }
    else if (waveType > 0.5 && waveType < 1.5) {
        squareWaveButton.setToggleState(true, dontSendNotification);
    }
    else if (waveType > 1.5 && waveType < 2.5) {
        triangleWaveButton.setToggleState(true, dontSendNotification);
    }
    else if (waveType > 2.5 && waveType < 3.5) {
        sawToothWaveButton.setToggleState(true, dontSendNotification);
    }
    else if (waveType > 3.5 && waveType < 4.5) {
        FMWaveButton.setToggleState(true, dontSendNotification);
    }
    else if (waveType > 4.5 && waveType < 5.5) {
        AMWaveButton.setToggleState(true, dontSendNotification);
    }
    else if (waveType > 5.5 && waveType < 6.5) {
        FMixWaveButton.setToggleState(true, dontSendNotification);
    }
    else {
        sineWaveButton.setToggleState(true, dontSendNotification);
    }
}

// This is our Slider::Listener callback, when the user drags a slider.
void AudioPluginAudioProcessorEditor::sliderValueChanged (Slider* slider)
{
    if (slider == &gainSlider)
    {
        // It's vital to use setParameterNotifyingHost to change any parameters that are automatable
        // by the host, rather than just modifying them directly, otherwise the host won't know
        // that they've changed.
        getProcessor()->setParameterNotifyingHost (AudioPluginAudioProcessor::gainParam,
                                                   (float) gainSlider.getValue());
    }
    else if (slider == &delaySlider)
    {
        getProcessor()->setParameterNotifyingHost (AudioPluginAudioProcessor::delayParam,
                                                   (float) delaySlider.getValue());
    }
}

// This is our Button::Listener callback, when the user drags a slider.
void AudioPluginAudioProcessorEditor::buttonClicked(Button* button)
{
    if (button == &sineWaveButton)
    {
        // It's vital to use setParameterNotifyingHost to change any parameters that are automatable
        // by the host, rather than just modifying them directly, otherwise the host won't know
        // that they've changed.
        getProcessor()->setParameterNotifyingHost (AudioPluginAudioProcessor::waveTypeParam, 0.0);
    }
    else if (button == &squareWaveButton)
    {
        getProcessor()->setParameterNotifyingHost (AudioPluginAudioProcessor::waveTypeParam, 1.0);
    }
    else if (button == &triangleWaveButton)
    {
        getProcessor()->setParameterNotifyingHost (AudioPluginAudioProcessor::waveTypeParam, 2.0);
    }
    else if (button == &sawToothWaveButton)
    {
        getProcessor()->setParameterNotifyingHost (AudioPluginAudioProcessor::waveTypeParam, 3.0);
    }
    else if (button == &FMWaveButton)
    {
        getProcessor()->setParameterNotifyingHost (AudioPluginAudioProcessor::waveTypeParam, 4.0);
    }
    else if (button == &AMWaveButton)
    {
        getProcessor()->setParameterNotifyingHost (AudioPluginAudioProcessor::waveTypeParam, 5.0);
    }
    else if (button == &FMixWaveButton)
    {
        getProcessor()->setParameterNotifyingHost (AudioPluginAudioProcessor::waveTypeParam, 6.0);
    }
    else
    {
        jassertfalse;
    }
}

//==============================================================================
// quick-and-dirty function to format a timecode string
static const String timeToTimecodeString (const double seconds)
{
    const double absSecs = fabs (seconds);
    
    const int hours =  (int) (absSecs / (60.0 * 60.0));
    const int mins  = ((int) (absSecs / 60.0)) % 60;
    const int secs  = ((int) absSecs) % 60;
    
    String s (seconds < 0 ? "-" : "");
    
    s << String (hours).paddedLeft ('0', 2) << ":"
    << String (mins) .paddedLeft ('0', 2) << ":"
    << String (secs) .paddedLeft ('0', 2) << ":"
    << String (roundToInt (absSecs * 1000) % 1000).paddedLeft ('0', 3);
    
    return s;
}

// quick-and-dirty function to format a bars/beats string
static const String ppqToBarsBeatsString (double ppq, double /*lastBarPPQ*/, int numerator, int denominator)
{
    if (numerator == 0 || denominator == 0)
        return "1|1|0";
    
    const int ppqPerBar = (numerator * 4 / denominator);
    const double beats  = (fmod (ppq, ppqPerBar) / ppqPerBar) * numerator;
    
    const int bar    = ((int) ppq) / ppqPerBar + 1;
    const int beat   = ((int) beats) + 1;
    const int ticks  = ((int) (fmod (beats, 1.0) * 960.0 + 0.5));
    
    String s;
    s << bar << '|' << beat << '|' << ticks;
    return s;
}

// Updates the text in our position label.
void AudioPluginAudioProcessorEditor::displayPositionInfo (const AudioPlayHead::CurrentPositionInfo& pos)
{
    lastDisplayedPosition = pos;
    String displayText;
    displayText.preallocateBytes (128);
    
    displayText << String (pos.bpm, 2) << " bpm, "
    << pos.timeSigNumerator << '/' << pos.timeSigDenominator
    << "  -  " << timeToTimecodeString (pos.timeInSeconds)
    << "  -  " << ppqToBarsBeatsString (pos.ppqPosition, pos.ppqPositionOfLastBarStart,
                                        pos.timeSigNumerator, pos.timeSigDenominator);
    
    if (pos.isRecording)
        displayText << "  (recording)";
    else if (pos.isPlaying)
        displayText << "  (playing)";
    
    infoLabel.setText (displayText, dontSendNotification);
}